#!/bin/sh

sbt_version="0.13.0-20130611-052157"
sbt="sbt-launch.jar" 
sbt_url="http://repo.typesafe.com/typesafe/ivy-snapshots/org.scala-sbt/sbt-launch/$sbt_version/$sbt"

# install sbt if missing (first run)
if [ ! -f $sbt ]; then
  echo "  - Downloading $sbt_url"
  curl -o $sbt $sbt_url
fi

java -Xms256M -Xmx2048M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -jar `dirname $0`/$sbt "$@"
